### PR TITLE
Python 3 Compatible

### PR DESCRIPTION
**Pull request by gfleetwood**
Hi,

Thanks for this repo. It's exactly what I need for a project. I made a couple of changes to make it work in Python 3.5.

* Added a lambda function to __main__.py to determine whether to use input or raw_input.

* Changed the TtsWatson.py variable dataToRead to an explicit empty byte variable.

* Enclosed print statements in parentheses.

I also did some minor formatting, including updating the README.md to say 'Python 2.7 or higher'. I tested my changes in Python 3.5 and a Python 2.7 virtual environment.

### CODE REVIEW

**Comment by ArthurHlt** [comment]
hi @gfleetwood ,

thanks for the work, it was a school project and I don't really want to maintain it (mostly because I don't have time anymore for that). If you want to maintain it/make some change let me know I will give you this repo (on github and pypi).

**Comment by gfleetwood** [comment]
@ArthurHlt I'm not sure how suited I am to do it, but I'll give it a go. Following the license would be no problem.

**Comment by ArthurHlt** [comment]
I'm doing the move

**Comment by ArthurHlt** [comment]
i forgot, can you please rename your actual fork

**Comment by gfleetwood** [comment]
OK. I'm kinda new to this. Does it matter what I rename it as?

**Comment by ArthurHlt** [comment]
I want to transfer you the ownership it does matter because it give you this repo but it can't transfer because you already have a repo named like that (your fork).

**Comment by gfleetwood** [comment]
Right. I changed the name.

**Comment by ArthurHlt** [comment]
well, i hvae this error 
> gfleetwood already has a repository in the ArthurHlt/tts-watson network

I merge this PR please delete your fork after that.

**Comment by gfleetwood** [comment]
I just deleted it.

**Pull request merged**
